#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 3

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
type = "path"
style = "plain"
foreground = "red"
template = "{{ .Path }} "

[blocks.segments.properties]
style = "agnoster_short"
max_depth = 4

[blocks.segments.properties.mapped_locations]
"~/www" = "î«„"
"~/dotfiles" = "ó±„…"
"~/Downloads" = "ó°‡š"
"~/.config" = "ï€“"

[[blocks.segments]]
type = "git"
style = "plain"
foreground = "cyan"
background = "transparent"
template = "{{ .HEAD }}{{ if gt .Behind 0 }} â‡£{{ end }}{{ if gt .Ahead 0 }} â‡¡{{ end }} "

[blocks.segments.properties]
branch_icon = "îœ¥ "
commit_icon = "@"
fetch_status = true

[blocks.segments.properties.mapped_branches]
"main" = "ğŸ‘ï¸ main"
"master" = "ğŸ’€ master"
"feat/*" = "ğŸš€ "
"bug/*" = "ğŸ› "
"component/*" = "ğŸ§± "

[[blocks.segments]]
type = "text"
style = "plain"
foreground = "red"
template = "ï¡ "
